# Generated by Django 4.2.5 on 2023-09-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancoAgenda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BancoAgenda',
        ),
    ]
