# Generated by Django 4.2.5 on 2023-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoAgenda', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancoagenda',
            name='data',
            field=models.DateField(verbose_name='Data do agendamento'),
        ),
    ]
