# Generated by Django 4.2.5 on 2023-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoAgenda', '0005_bancoagenda_date_joine_bancoagenda_email_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancoagenda',
            name='email_usuario',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email do usuário'),
        ),
        migrations.AlterField(
            model_name='bancoagenda',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Senha do usuário'),
        ),
    ]
