# Generated by Django 4.2.5 on 2023-10-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoAgenda', '0006_alter_bancoagenda_email_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancoagenda',
            name='assunto',
            field=models.CharField(max_length=100, verbose_name='Assunto do agendamento'),
        ),
        migrations.AlterField(
            model_name='bancoagenda',
            name='celular',
            field=models.CharField(max_length=100, verbose_name='Celular do agendamento'),
        ),
        migrations.AlterField(
            model_name='bancoagenda',
            name='data',
            field=models.DateField(verbose_name='Data do agendamento'),
        ),
        migrations.AlterField(
            model_name='bancoagenda',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email do agendamento'),
        ),
        migrations.AlterField(
            model_name='bancoagenda',
            name='nome_agenda',
            field=models.CharField(max_length=100, verbose_name='Nome do agendamento'),
        ),
    ]
