# Generated by Django 4.2.5 on 2023-10-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoAgenda', '0007_alter_bancoagenda_assunto_alter_bancoagenda_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancoagenda',
            name='data',
            field=models.DateField(null=True, verbose_name='Data do agendamento'),
        ),
    ]
